[project]
name = "hexlet-code"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.4",
]

[project.scripts]
gendiff = 'gendiff.scripts.gendiff:main'
